//! Generate a typed client from a rhypedb SDL schema.
//!
//! v1 emits a **Rust** module of serde-deriving row structs — one `pub struct`
//! per object type, carrying that type's **scalar** fields (the `fields` payload
//! a `POST /query` returns). Each field is `Option<T>` so a column-projected or
//! otherwise partial response still deserializes. Relations and vector fields are
//! not scalar columns in `fields`, so they are documented on the struct but not
//! emitted as data fields.
//!
//! Input is a parsed [`Schema`] (the CLI reads an SDL file via
//! `rhypedb_schema::parser::parse_schema`, or you can fetch the live schema from
//! the server's `GET /schema` endpoint). Future increments add a typed query
//! builder and a JS/TS target.

use rhypedb_schema::{FieldType, ScalarType, Schema, TypeDef};

const HEADER: &str = "\
// Code generated by rhypedb-codegen — DO NOT EDIT.
//
// Typed row structs for a rhypedb schema. Each struct mirrors an object type's
// scalar fields — the `fields` map returned by `POST /query` (the object `id`
// lives in the response envelope, not in `fields`). Fields are `Option<T>` so a
// projected/partial response still deserializes. Relations and vector fields are
// documented per struct but are not scalar columns.
//
// Use as a module, e.g. `mod client;`. Requires `serde` (with `derive`) and
// `serde_json`. `DateTime` reads/writes as an RFC 3339 `String`, `Bytes` as a
// base64 `String`, and `Json` as a `serde_json::Value` — all round-trip.
//
// Read queries: build a typed `Query` from a constructor (e.g. `User::all()`),
// chain `.filter(..)` / `.limit(..)`, send `.build()` as the `query` of a
// `POST /query` body, then parse the response with `Row::<User>::from_response`.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};
";

const RUNTIME: &str = r#"
/// A typed query string targeting one object type. Build it from a typed
/// constructor (e.g. `User::all()`), optionally chain `.filter(..)` / `.limit(..)`,
/// then send `.build()` as the `query` field of a `POST /query` body and parse
/// the response with `Row`. This is a thin string builder; the server validates
/// query composition.
#[derive(Debug, Clone)]
pub struct Query<T> {
    text: String,
    _row: std::marker::PhantomData<fn() -> T>,
}

impl<T> Query<T> {
    fn raw(text: String) -> Self {
        Query { text, _row: std::marker::PhantomData }
    }
    /// Append `.filter(<predicate>)`, e.g. `.filter(".age > 18")`.
    pub fn filter(mut self, predicate: &str) -> Self {
        self.text.push_str(".filter(");
        self.text.push_str(predicate);
        self.text.push(')');
        self
    }
    /// Append `.limit(<n>)`.
    pub fn limit(mut self, n: u64) -> Self {
        self.text.push_str(&format!(".limit({n})"));
        self
    }
    /// Consume the builder, returning the query string.
    pub fn build(self) -> String {
        self.text
    }
    /// Borrow the query string.
    pub fn as_str(&self) -> &str {
        &self.text
    }
}

impl<T> std::fmt::Display for Query<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.text)
    }
}

/// A query-result row: the object `id` from the `POST /query` envelope plus its
/// typed scalar fields.
#[derive(Debug, Clone)]
pub struct Row<T> {
    pub id: u64,
    pub data: T,
}

impl<T: serde::de::DeserializeOwned> Row<T> {
    /// Parse one `{ "type", "id", "fields": { .. } }` object value.
    pub fn from_object(v: &serde_json::Value) -> Result<Self, String> {
        let id = v
            .get("id")
            .and_then(serde_json::Value::as_u64)
            .ok_or_else(|| String::from("object missing numeric `id`"))?;
        let fields = v.get("fields").cloned().unwrap_or(serde_json::Value::Null);
        let data = serde_json::from_value(fields).map_err(|e| e.to_string())?;
        Ok(Row { id, data })
    }

    /// Parse a `POST /query` response — either `{ "object": { .. } }` (single) or
    /// `{ "objects": [ .. ] }` (list) — into typed rows.
    pub fn from_response(resp: &serde_json::Value) -> Result<Vec<Self>, String> {
        if let Some(one) = resp.get("object") {
            return Ok(vec![Self::from_object(one)?]);
        }
        if let Some(arr) = resp.get("objects").and_then(serde_json::Value::as_array) {
            return arr.iter().map(Self::from_object).collect();
        }
        Err(String::from("response had neither `object` nor `objects`"))
    }
}

/// Quote + escape a string as a rhypedb query string literal.
fn rhypedb_str_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Format a numeric/bool value as a query literal. `Debug` keeps floats
/// float-shaped (`1.0`, `1.5`, `1e20`) and ints int-shaped (`30`); both coerce to
/// the field's declared scalar type on the server.
fn rhypedb_lit<T: std::fmt::Debug>(v: &T) -> String {
    format!("{v:?}")
}

/// Format a JSON value as a raw rhypedb JSON literal — the query parser accepts a
/// JSON object/array in value position; scalar JSON values round-trip too.
fn rhypedb_json_lit(v: &serde_json::Value) -> String {
    v.to_string()
}
"#;

/// Generate a Rust module (source text) of typed row structs for `schema`.
///
/// Types are emitted sorted by name (the schema's `HashMap` order is
/// nondeterministic); each struct's scalar fields are emitted in declaration
/// order. The output is deterministic for a given schema.
pub fn generate_rust(schema: &Schema) -> String {
    let mut out = String::from(HEADER);
    out.push_str(RUNTIME);

    let mut names: Vec<&String> = schema.types.keys().collect();
    names.sort();

    for name in names {
        out.push('\n');
        emit_struct(&mut out, &schema.types[name]);
    }
    out
}

fn emit_struct(out: &mut String, td: &TypeDef) {
    out.push_str(&format!("/// Scalar fields of `type {}`.\n", td.name));
    // Document relations / vectors (not scalar columns) for the reader.
    for f in &td.fields {
        match &f.field_type {
            FieldType::Relation(rel) => out.push_str(&format!(
                "/// - relation `{}` -> `{}`{}\n",
                f.name,
                rel.target_type,
                if rel.is_many { " (many)" } else { "" }
            )),
            FieldType::Vector(v) => {
                out.push_str(&format!("/// - vector `{}` (dim {})\n", f.name, v.dimensions))
            }
            FieldType::Scalar(_) => {}
        }
    }

    out.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", td.name));
    for f in &td.fields {
        let FieldType::Scalar(s) = &f.field_type else {
            continue;
        };
        let ident = ident_for(&f.name);
        if ident != f.name {
            // Raw-ident or otherwise rewritten name — keep the wire name on serde.
            out.push_str(&format!("    #[serde(default, rename = \"{}\")]\n", f.name));
        } else {
            out.push_str("    #[serde(default)]\n");
        }
        out.push_str(&format!("    pub {ident}: Option<{}>,\n", scalar_rust_type(s)));
    }
    out.push_str("}\n");

    // Type- and field-name constants for building queries by hand.
    let scalar_fields: Vec<String> = td
        .fields
        .iter()
        .filter(|f| matches!(f.field_type, FieldType::Scalar(_)))
        .map(|f| format!("\"{}\"", f.name))
        .collect();
    out.push_str(&format!("\nimpl {} {{\n", td.name));
    out.push_str(&format!(
        "    pub const TYPE_NAME: &'static str = \"{}\";\n",
        td.name
    ));
    out.push_str(&format!(
        "    pub const FIELDS: &'static [&'static str] = &[{}];\n",
        scalar_fields.join(", ")
    ));

    // Typed read-query constructors → `Query<Self>`.
    let t = &td.name;
    out.push_str(&format!(
        "\n    /// `{t}` — all objects of this type.\n    pub fn all() -> Query<{t}> {{ Query::raw(String::from(\"{t}\")) }}\n"
    ));
    out.push_str(&format!(
        "    /// `{t}.get(id)` — one object by id.\n    pub fn get(id: u64) -> Query<{t}> {{ Query::raw(format!(\"{t}.get({{id}})\")) }}\n"
    ));
    out.push_str(&format!(
        "    /// `{t}.filter(predicate)` — e.g. `{t}::filter(\".age > 18\")`.\n    pub fn filter(predicate: &str) -> Query<{t}> {{ Query::raw(format!(\"{t}.filter({{predicate}})\")) }}\n"
    ));

    // Typed create from a row's set (`Some`) fields. Every scalar is settable: a
    // `DateTime` row field is an RFC 3339 string, `Bytes` a base64 string (both
    // coerce server-side), and `Json` emits a raw JSON literal.
    out.push_str(&format!(
        "\n    /// `{t}.create({{ .. }})` from this row's set (`Some`) fields.\n    pub fn create(row: &{t}) -> Query<{t}> {{\n        let mut parts: Vec<String> = Vec::new();\n"
    ));
    for f in td.fields.iter().filter(|f| matches!(&f.field_type, FieldType::Scalar(s) if is_creatable_scalar(s))) {
        let ident = ident_for(&f.name);
        let key = &f.name;
        let helper = match &f.field_type {
            // DateTime/Bytes ride in the row as RFC3339 / base64 strings.
            FieldType::Scalar(
                ScalarType::String | ScalarType::DateTime | ScalarType::Bytes,
            ) => "rhypedb_str_lit",
            FieldType::Scalar(ScalarType::Json) => "rhypedb_json_lit",
            _ => "rhypedb_lit",
        };
        out.push_str(&format!(
            "        if let Some(v) = &row.{ident} {{ parts.push(format!(\"{key}: {{}}\", {helper}(v))); }}\n"
        ));
    }
    out.push_str(&format!(
        "        Query::raw(format!(\"{t}.create({{{{ {{}} }}}})\", parts.join(\", \")))\n    }}\n"
    ));

    out.push_str("}\n");
}

/// Map a schema scalar type to its Rust representation. `DateTime` reads back as
/// an RFC 3339 `String` and `Bytes` as a base64 `String`; `Json` maps to
/// `serde_json::Value`.
fn scalar_rust_type(s: &ScalarType) -> &'static str {
    match s {
        ScalarType::String => "String",
        ScalarType::U32 => "u32",
        ScalarType::U64 => "u64",
        ScalarType::I32 => "i32",
        ScalarType::I64 => "i64",
        ScalarType::F32 => "f32",
        ScalarType::F64 => "f64",
        ScalarType::Bool => "bool",
        ScalarType::DateTime => "String",
        ScalarType::Bytes => "String",
        ScalarType::Json => "serde_json::Value",
    }
}

/// Scalar types settable via a query literal at `create` time. Every scalar is
/// now wired (DateTime ← RFC 3339 string, Bytes ← base64 string, Json ← raw JSON
/// literal), so all are creatable.
fn is_creatable_scalar(_s: &ScalarType) -> bool {
    true
}

/// A valid Rust field identifier for a schema field name. SDL field names are
/// `[A-Za-z_][A-Za-z0-9_]*`, so the only adjustment needed is escaping Rust
/// keywords as raw identifiers (`type` -> `r#type`).
fn ident_for(name: &str) -> String {
    if is_raw_safe_keyword(name) {
        format!("r#{name}")
    } else if is_bare_keyword(name) {
        // Keywords that cannot be raw identifiers (`self`, `crate`, ...) — suffix.
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Keywords that are legal as raw identifiers (`r#name`).
fn is_raw_safe_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "break" | "const" | "continue" | "else" | "enum" | "false" | "fn" | "for" | "if"
            | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move" | "mut" | "pub" | "ref"
            | "return" | "static" | "struct" | "trait" | "true" | "type" | "unsafe" | "use"
            | "where" | "while" | "async" | "await" | "dyn" | "abstract" | "become" | "box"
            | "do" | "final" | "macro" | "override" | "priv" | "typeof" | "unsized" | "virtual"
            | "yield" | "try"
    )
}

/// The handful of keywords that are NOT valid as raw identifiers.
fn is_bare_keyword(name: &str) -> bool {
    matches!(name, "crate" | "self" | "super" | "Self")
}

const TS_HEADER: &str = r#"// Code generated by rhypedb-codegen — DO NOT EDIT.
//
// Typed TypeScript client for a rhypedb schema. Per object type: an `interface`
// of its scalar fields (each optional, so a column-projected POST /query response
// still type-checks) and a value namespace of typed query constructors. Plus a
// `Query` string builder and a `parseResponse` helper that turns the
// { object | objects } envelope into { id, data } rows.
//
// `DateTime`/`Bytes` are typed `string`; `Json` is `unknown`. 64-bit integer
// fields are `number` and lose precision beyond 2^53 (a JSON-number wire limit).
//
// `Row` is a type-only export — under `verbatimModuleSyntax` or Node's
// type-stripping, import it with `type`, e.g.
//   import { User, parseResponse, type Row } from "./client.ts";

export class Query {
  private text: string;
  constructor(text: string) { this.text = text; }
  /** Append `.filter(<predicate>)`, e.g. `.filter(".age > 18")`. */
  filter(predicate: string): this { this.text += `.filter(${predicate})`; return this; }
  /** Append `.limit(<n>)`. */
  limit(n: number): this { this.text += `.limit(${n})`; return this; }
  /** The query string for the `query` field of a POST /query body. */
  build(): string { return this.text; }
  toString(): string { return this.text; }
}

export interface Row<T> { id: number; data: T; }

/**
 * Parse a POST /query response — `{ object }` (single) or `{ objects }` (list) —
 * into typed rows. Annotate the element type at the call site, e.g.
 * `parseResponse<User>(json)`.
 */
export function parseResponse<T>(resp: any): Array<Row<T>> {
  const toRow = (o: any): Row<T> => ({ id: o.id as number, data: (o.fields ?? {}) as T });
  if (resp && resp.object) return [toRow(resp.object)];
  if (resp && Array.isArray(resp.objects)) return resp.objects.map(toRow);
  throw new Error("response had neither `object` nor `objects`");
}

/** Quote + escape a string as a rhypedb query string literal. */
function rhypedbStr(s: string): string {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

/** Format a number/boolean as a query literal (coerced to the field type server-side). */
function rhypedbLit(v: number | boolean): string {
  return String(v);
}

/** Format a JSON value as a raw rhypedb JSON literal (object/array, or a scalar). */
function rhypedbJson(v: unknown): string {
  return JSON.stringify(v);
}
"#;

/// Generate a TypeScript module (source text) of typed interfaces + query
/// constructors for `schema`. Mirrors [`generate_rust`]'s shape: one `interface`
/// per type (scalar fields, each optional) plus a same-named value namespace with
/// `all()` / `get(id)` / `filter(predicate)` returning a [`Query`]-builder string,
/// and a generic `Row` / `parseResponse` for the response envelope.
pub fn generate_typescript(schema: &Schema) -> String {
    let mut out = String::from(TS_HEADER);

    let mut names: Vec<&String> = schema.types.keys().collect();
    names.sort();

    for name in names {
        emit_ts_type(&mut out, &schema.types[name]);
    }
    out
}

fn emit_ts_type(out: &mut String, td: &TypeDef) {
    out.push_str(&format!("\n/** Scalar fields of `type {}`.", td.name));
    for f in &td.fields {
        match &f.field_type {
            FieldType::Relation(rel) => out.push_str(&format!(
                "\n *  - relation `{}` -> `{}`{}",
                f.name,
                rel.target_type,
                if rel.is_many { " (many)" } else { "" }
            )),
            FieldType::Vector(v) => {
                out.push_str(&format!("\n *  - vector `{}` (dim {})", f.name, v.dimensions))
            }
            FieldType::Scalar(_) => {}
        }
    }
    out.push_str(" */\n");

    out.push_str(&format!("export interface {} {{\n", td.name));
    for f in &td.fields {
        if let FieldType::Scalar(s) = &f.field_type {
            // SDL field names are valid TS property names (keywords are legal as
            // property names in TS), so no escaping is needed.
            out.push_str(&format!("  {}?: {};\n", f.name, scalar_ts_type(s)));
        }
    }
    out.push_str("}\n");

    let scalar_fields: Vec<String> = td
        .fields
        .iter()
        .filter(|f| matches!(f.field_type, FieldType::Scalar(_)))
        .map(|f| format!("\"{}\"", f.name))
        .collect();
    let t = &td.name;
    out.push_str(&format!("export const {t} = {{\n"));
    out.push_str(&format!("  TYPE_NAME: \"{t}\" as const,\n"));
    out.push_str(&format!(
        "  FIELDS: [{}] as const,\n",
        scalar_fields.join(", ")
    ));
    out.push_str(&format!(
        "  /** `{t}` — all objects of this type. */\n  all(): Query {{ return new Query(\"{t}\"); }},\n"
    ));
    out.push_str(&format!(
        "  /** `{t}.get(id)` — one object by id. */\n  get(id: number): Query {{ return new Query(`{t}.get(${{id}})`); }},\n"
    ));
    out.push_str(&format!(
        "  /** `{t}.filter(predicate)`. */\n  filter(predicate: string): Query {{ return new Query(`{t}.filter(${{predicate}})`); }},\n"
    ));

    // Typed create from a row's set fields. DateTime (RFC 3339) + Bytes (base64)
    // ride as strings; Json emits a raw JSON literal.
    out.push_str(&format!(
        "  /** `{t}.create({{ .. }})` from `row`'s set fields. */\n  create(row: {t}): Query {{\n    const parts: string[] = [];\n"
    ));
    for f in td.fields.iter().filter(|f| matches!(&f.field_type, FieldType::Scalar(s) if is_creatable_scalar(s))) {
        let key = &f.name;
        let helper = match &f.field_type {
            FieldType::Scalar(
                ScalarType::String | ScalarType::DateTime | ScalarType::Bytes,
            ) => "rhypedbStr",
            FieldType::Scalar(ScalarType::Json) => "rhypedbJson",
            _ => "rhypedbLit",
        };
        out.push_str(&format!(
            "    if (row.{key} !== undefined) parts.push(`{key}: ${{{helper}(row.{key})}}`);\n"
        ));
    }
    out.push_str(&format!(
        "    return new Query(`{t}.create({{ ${{parts.join(\", \")}} }})`);\n  }},\n"
    ));

    out.push_str("};\n");
}

/// Map a schema scalar type to its TypeScript representation. 64-bit integers map
/// to `number` (lossy past 2^53 over JSON); `DateTime`/`Bytes` to `string`;
/// `Json` to `unknown`.
fn scalar_ts_type(s: &ScalarType) -> &'static str {
    match s {
        ScalarType::String | ScalarType::DateTime | ScalarType::Bytes => "string",
        ScalarType::U32
        | ScalarType::U64
        | ScalarType::I32
        | ScalarType::I64
        | ScalarType::F32
        | ScalarType::F64 => "number",
        ScalarType::Bool => "boolean",
        ScalarType::Json => "unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rhypedb_schema::parser::parse_schema;

    fn gen_rs(sdl: &str) -> String {
        generate_rust(&parse_schema(sdl).unwrap())
    }

    fn gen_ts(sdl: &str) -> String {
        generate_typescript(&parse_schema(sdl).unwrap())
    }

    #[test]
    fn emits_typed_scalar_struct_with_constants() {
        let code = gen_rs(r#"type User { name: String @unique  age: i64 @indexed  active: Bool }"#);
        assert!(code.contains("pub struct User {"));
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains("pub age: Option<i64>,"));
        assert!(code.contains("pub active: Option<bool>,"));
        assert!(code.contains("pub const TYPE_NAME: &'static str = \"User\";"));
        assert!(code.contains(r#"pub const FIELDS: &'static [&'static str] = &["name", "age", "active"];"#));
    }

    #[test]
    fn maps_every_scalar_kind() {
        let code = gen_rs(
            r#"type T {
                s: String  a: u32  b: u64  c: i32  d: i64  e: f32  f: f64
                g: Bool  h: DateTime  i: Bytes  j: Json
            }"#,
        );
        for needle in [
            "pub s: Option<String>,",
            "pub a: Option<u32>,",
            "pub b: Option<u64>,",
            "pub c: Option<i32>,",
            "pub d: Option<i64>,",
            "pub e: Option<f32>,",
            "pub f: Option<f64>,",
            "pub g: Option<bool>,",
            "pub h: Option<String>,",  // DateTime -> String
            "pub i: Option<String>,",  // Bytes -> String
            "pub j: Option<serde_json::Value>,",
        ] {
            assert!(code.contains(needle), "missing `{needle}` in:\n{code}");
        }
    }

    #[test]
    fn relations_and_vectors_are_doc_comments_not_fields() {
        let code = gen_rs(
            r#"
            type Author {
                name: String
                books: [Book] @inverse(Book.author)
                bio_vec: Vector<384>
            }
            type Book { title: String  author: Author }
            "#,
        );
        // Relation + vector documented, not emitted as struct fields.
        assert!(code.contains("/// - relation `books` -> `Book` (many)"));
        assert!(code.contains("/// - vector `bio_vec` (dim 384)"));
        assert!(!code.contains("pub books:"));
        assert!(!code.contains("pub bio_vec:"));
        // Only the scalar `name` is a field; FIELDS reflects that.
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains(r#"pub const FIELDS: &'static [&'static str] = &["name"];"#));
    }

    #[test]
    fn keyword_field_becomes_raw_ident_with_serde_rename() {
        let code = gen_rs(r#"type Event { type: String  match: i64 }"#);
        assert!(code.contains("#[serde(default, rename = \"type\")]"));
        assert!(code.contains("pub r#type: Option<String>,"));
        assert!(code.contains("pub r#match: Option<i64>,"));
    }

    #[test]
    fn types_are_sorted_for_determinism() {
        let code = gen_rs(r#"type Zebra { a: i32 }  type Apple { b: i32 }  type Mango { c: i32 }"#);
        let apple = code.find("struct Apple").unwrap();
        let mango = code.find("struct Mango").unwrap();
        let zebra = code.find("struct Zebra").unwrap();
        assert!(apple < mango && mango < zebra, "types must be name-sorted");
    }

    #[test]
    fn emits_query_runtime_and_typed_constructors() {
        let code = gen_rs(r#"type User { name: String  age: i64 }"#);
        // Generic runtime types emitted once.
        assert!(code.contains("pub struct Query<T>"));
        assert!(code.contains("pub struct Row<T>"));
        assert!(code.contains("pub fn from_response(resp: &serde_json::Value)"));
        assert!(code.contains("pub fn filter(mut self, predicate: &str) -> Self"));
        assert!(code.contains("pub fn limit(mut self, n: u64) -> Self"));
        // Per-type typed constructors.
        assert!(code.contains("pub fn all() -> Query<User> { Query::raw(String::from(\"User\")) }"));
        assert!(code.contains("pub fn get(id: u64) -> Query<User> { Query::raw(format!(\"User.get({id})\")) }"));
        assert!(code.contains("pub fn filter(predicate: &str) -> Query<User> { Query::raw(format!(\"User.filter({predicate})\")) }"));
    }

    #[test]
    fn emits_typed_create() {
        let code = gen_rs(
            r#"type User { name: String  age: i64  score: f64  active: Bool  created: DateTime  blob: Bytes  meta: Json }"#,
        );
        assert!(code.contains("pub fn create(row: &User) -> Query<User> {"));
        assert!(code.contains(r#"if let Some(v) = &row.name { parts.push(format!("name: {}", rhypedb_str_lit(v))); }"#));
        assert!(code.contains(r#"if let Some(v) = &row.age { parts.push(format!("age: {}", rhypedb_lit(v))); }"#));
        assert!(code.contains(r#"if let Some(v) = &row.score { parts.push(format!("score: {}", rhypedb_lit(v))); }"#));
        assert!(code.contains(r#"if let Some(v) = &row.active { parts.push(format!("active: {}", rhypedb_lit(v))); }"#));
        // DateTime/Bytes ride as strings; Json emits a raw JSON literal.
        assert!(code.contains(r#"if let Some(v) = &row.created { parts.push(format!("created: {}", rhypedb_str_lit(v))); }"#));
        assert!(code.contains(r#"if let Some(v) = &row.blob { parts.push(format!("blob: {}", rhypedb_str_lit(v))); }"#));
        assert!(code.contains(r#"if let Some(v) = &row.meta { parts.push(format!("meta: {}", rhypedb_json_lit(v))); }"#));
        assert!(code.contains("fn rhypedb_str_lit(s: &str) -> String"));
        assert!(code.contains("fn rhypedb_lit<T: std::fmt::Debug>(v: &T) -> String"));
        assert!(code.contains("fn rhypedb_json_lit(v: &serde_json::Value) -> String"));
    }

    #[test]
    fn ts_emits_typed_create() {
        let code = gen_ts(
            r#"type User { name: String  age: i64  active: Bool  created: DateTime  meta: Json }"#,
        );
        assert!(code.contains("create(row: User): Query {"));
        assert!(code.contains("if (row.name !== undefined) parts.push(`name: ${rhypedbStr(row.name)}`);"));
        assert!(code.contains("if (row.age !== undefined) parts.push(`age: ${rhypedbLit(row.age)}`);"));
        assert!(code.contains("if (row.active !== undefined) parts.push(`active: ${rhypedbLit(row.active)}`);"));
        // DateTime rides as a string; Json emits a raw JSON literal.
        assert!(code.contains("if (row.created !== undefined) parts.push(`created: ${rhypedbStr(row.created)}`);"));
        assert!(code.contains("if (row.meta !== undefined) parts.push(`meta: ${rhypedbJson(row.meta)}`);"));
        assert!(code.contains("function rhypedbStr(s: string): string"));
        assert!(code.contains("function rhypedbLit(v: number | boolean): string"));
        assert!(code.contains("function rhypedbJson(v: unknown): string"));
    }

    #[test]
    fn ts_emits_interface_namespace_and_runtime() {
        let code = gen_ts(
            r#"type User { name: String @unique  age: i64  active: Bool  meta: Json }
               type Post { title: String  author: User }"#,
        );
        // Runtime emitted once.
        assert!(code.contains("export class Query {"));
        assert!(code.contains("export interface Row<T> { id: number; data: T; }"));
        assert!(code.contains("export function parseResponse<T>(resp: any): Array<Row<T>>"));
        // Interface (scalar fields, optional) — types sorted so Post before User.
        assert!(code.find("interface Post").unwrap() < code.find("interface User").unwrap());
        assert!(code.contains("export interface User {"));
        assert!(code.contains("  name?: string;"));
        assert!(code.contains("  age?: number;"));
        assert!(code.contains("  active?: boolean;"));
        assert!(code.contains("  meta?: unknown;"));
        // Value namespace with typed constructors.
        assert!(code.contains("export const User = {"));
        assert!(code.contains(r#"  TYPE_NAME: "User" as const,"#));
        assert!(code.contains(r#"  FIELDS: ["name", "age", "active", "meta"] as const,"#));
        assert!(code.contains(r#"  all(): Query { return new Query("User"); },"#));
        assert!(code.contains("  get(id: number): Query { return new Query(`User.get(${id})`); },"));
        assert!(code.contains("  filter(predicate: string): Query { return new Query(`User.filter(${predicate})`); },"));
    }

    #[test]
    fn ts_relations_and_vectors_are_jsdoc_not_fields() {
        let code = gen_ts(
            r#"type Author { name: String  books: [Book] @inverse(Book.author)  bio: Vector<384> }
               type Book { title: String  author: Author }"#,
        );
        assert!(code.contains(" *  - relation `books` -> `Book` (many)"));
        assert!(code.contains(" *  - vector `bio` (dim 384)"));
        // Not interface members.
        assert!(!code.contains("books?:"));
        assert!(!code.contains("bio?:"));
    }

    #[test]
    fn output_is_syntactically_valid_rust() {
        let code = gen_rs(
            r#"
            type User {
                name: String @unique
                age: i64 @indexed
                type: Bool
                posts: [Post] @inverse(Post.author) @on_delete(cascade)
                embedding: Vector<384> @vectorize(source: "name", model: "m") @index(hnsw, metric: cosine)
                meta: Json
                created: DateTime
                blob: Bytes
            }
            type Post { title: String  author: User }
            type Empty { only_a_relation: User }
            "#,
        );
        syn::parse_file(&code)
            .unwrap_or_else(|e| panic!("generated code is not valid Rust: {e}\n---\n{code}"));
    }
}
