//! Generate a typed client from a rhypedb SDL schema.
//!
//! v1 emits a **Rust** module of serde-deriving row structs — one `pub struct`
//! per object type, carrying that type's **scalar** fields (the `fields` payload
//! a `POST /query` returns). Each field is `Option<T>` so a column-projected or
//! otherwise partial response still deserializes. Relations and vector fields are
//! not scalar columns in `fields`, so they are documented on the struct but not
//! emitted as data fields.
//!
//! Input is a parsed [`Schema`] (the CLI reads an SDL file via
//! `rhypedb_schema::parser::parse_schema`, or you can fetch the live schema from
//! the server's `GET /schema` endpoint). Future increments add a typed query
//! builder and a JS/TS target.

use rhypedb_schema::{FieldType, ScalarType, Schema, TypeDef};

const HEADER: &str = "\
// Code generated by rhypedb-codegen — DO NOT EDIT.
//
// Typed row structs for a rhypedb schema. Each struct mirrors an object type's
// scalar fields — the `fields` map returned by `POST /query` (the object `id`
// lives in the response envelope, not in `fields`). Fields are `Option<T>` so a
// projected/partial response still deserializes. Relations and vector fields are
// documented per struct but are not scalar columns.
//
// Use as a module, e.g. `mod client;`. Requires `serde` (with `derive`) and
// `serde_json`. `DateTime` is represented as a `String`; `Bytes` is currently
// returned by `/query` only as a placeholder and does not round-trip.
//
// Read queries: build a typed `Query` from a constructor (e.g. `User::all()`),
// chain `.filter(..)` / `.limit(..)`, send `.build()` as the `query` of a
// `POST /query` body, then parse the response with `Row::<User>::from_response`.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};
";

const RUNTIME: &str = r#"
/// A typed query string targeting one object type. Build it from a typed
/// constructor (e.g. `User::all()`), optionally chain `.filter(..)` / `.limit(..)`,
/// then send `.build()` as the `query` field of a `POST /query` body and parse
/// the response with `Row`. This is a thin string builder; the server validates
/// query composition.
#[derive(Debug, Clone)]
pub struct Query<T> {
    text: String,
    _row: std::marker::PhantomData<fn() -> T>,
}

impl<T> Query<T> {
    fn raw(text: String) -> Self {
        Query { text, _row: std::marker::PhantomData }
    }
    /// Append `.filter(<predicate>)`, e.g. `.filter(".age > 18")`.
    pub fn filter(mut self, predicate: &str) -> Self {
        self.text.push_str(".filter(");
        self.text.push_str(predicate);
        self.text.push(')');
        self
    }
    /// Append `.limit(<n>)`.
    pub fn limit(mut self, n: u64) -> Self {
        self.text.push_str(&format!(".limit({n})"));
        self
    }
    /// Consume the builder, returning the query string.
    pub fn build(self) -> String {
        self.text
    }
    /// Borrow the query string.
    pub fn as_str(&self) -> &str {
        &self.text
    }
}

impl<T> std::fmt::Display for Query<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.text)
    }
}

/// A query-result row: the object `id` from the `POST /query` envelope plus its
/// typed scalar fields.
#[derive(Debug, Clone)]
pub struct Row<T> {
    pub id: u64,
    pub data: T,
}

impl<T: serde::de::DeserializeOwned> Row<T> {
    /// Parse one `{ "type", "id", "fields": { .. } }` object value.
    pub fn from_object(v: &serde_json::Value) -> Result<Self, String> {
        let id = v
            .get("id")
            .and_then(serde_json::Value::as_u64)
            .ok_or_else(|| String::from("object missing numeric `id`"))?;
        let fields = v.get("fields").cloned().unwrap_or(serde_json::Value::Null);
        let data = serde_json::from_value(fields).map_err(|e| e.to_string())?;
        Ok(Row { id, data })
    }

    /// Parse a `POST /query` response — either `{ "object": { .. } }` (single) or
    /// `{ "objects": [ .. ] }` (list) — into typed rows.
    pub fn from_response(resp: &serde_json::Value) -> Result<Vec<Self>, String> {
        if let Some(one) = resp.get("object") {
            return Ok(vec![Self::from_object(one)?]);
        }
        if let Some(arr) = resp.get("objects").and_then(serde_json::Value::as_array) {
            return arr.iter().map(Self::from_object).collect();
        }
        Err(String::from("response had neither `object` nor `objects`"))
    }
}
"#;

/// Generate a Rust module (source text) of typed row structs for `schema`.
///
/// Types are emitted sorted by name (the schema's `HashMap` order is
/// nondeterministic); each struct's scalar fields are emitted in declaration
/// order. The output is deterministic for a given schema.
pub fn generate_rust(schema: &Schema) -> String {
    let mut out = String::from(HEADER);
    out.push_str(RUNTIME);

    let mut names: Vec<&String> = schema.types.keys().collect();
    names.sort();

    for name in names {
        out.push('\n');
        emit_struct(&mut out, &schema.types[name]);
    }
    out
}

fn emit_struct(out: &mut String, td: &TypeDef) {
    out.push_str(&format!("/// Scalar fields of `type {}`.\n", td.name));
    // Document relations / vectors (not scalar columns) for the reader.
    for f in &td.fields {
        match &f.field_type {
            FieldType::Relation(rel) => out.push_str(&format!(
                "/// - relation `{}` -> `{}`{}\n",
                f.name,
                rel.target_type,
                if rel.is_many { " (many)" } else { "" }
            )),
            FieldType::Vector(v) => {
                out.push_str(&format!("/// - vector `{}` (dim {})\n", f.name, v.dimensions))
            }
            FieldType::Scalar(_) => {}
        }
    }

    out.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", td.name));
    for f in &td.fields {
        let FieldType::Scalar(s) = &f.field_type else {
            continue;
        };
        let ident = ident_for(&f.name);
        if ident != f.name {
            // Raw-ident or otherwise rewritten name — keep the wire name on serde.
            out.push_str(&format!("    #[serde(default, rename = \"{}\")]\n", f.name));
        } else {
            out.push_str("    #[serde(default)]\n");
        }
        out.push_str(&format!("    pub {ident}: Option<{}>,\n", scalar_rust_type(s)));
    }
    out.push_str("}\n");

    // Type- and field-name constants for building queries by hand.
    let scalar_fields: Vec<String> = td
        .fields
        .iter()
        .filter(|f| matches!(f.field_type, FieldType::Scalar(_)))
        .map(|f| format!("\"{}\"", f.name))
        .collect();
    out.push_str(&format!("\nimpl {} {{\n", td.name));
    out.push_str(&format!(
        "    pub const TYPE_NAME: &'static str = \"{}\";\n",
        td.name
    ));
    out.push_str(&format!(
        "    pub const FIELDS: &'static [&'static str] = &[{}];\n",
        scalar_fields.join(", ")
    ));

    // Typed read-query constructors → `Query<Self>`.
    let t = &td.name;
    out.push_str(&format!(
        "\n    /// `{t}` — all objects of this type.\n    pub fn all() -> Query<{t}> {{ Query::raw(String::from(\"{t}\")) }}\n"
    ));
    out.push_str(&format!(
        "    /// `{t}.get(id)` — one object by id.\n    pub fn get(id: u64) -> Query<{t}> {{ Query::raw(format!(\"{t}.get({{id}})\")) }}\n"
    ));
    out.push_str(&format!(
        "    /// `{t}.filter(predicate)` — e.g. `{t}::filter(\".age > 18\")`.\n    pub fn filter(predicate: &str) -> Query<{t}> {{ Query::raw(format!(\"{t}.filter({{predicate}})\")) }}\n"
    ));

    out.push_str("}\n");
}

/// Map a schema scalar type to its Rust representation. `DateTime` and `Bytes`
/// fall back to `String` (their `/query` JSON form today); `Json` maps to
/// `serde_json::Value`.
fn scalar_rust_type(s: &ScalarType) -> &'static str {
    match s {
        ScalarType::String => "String",
        ScalarType::U32 => "u32",
        ScalarType::U64 => "u64",
        ScalarType::I32 => "i32",
        ScalarType::I64 => "i64",
        ScalarType::F32 => "f32",
        ScalarType::F64 => "f64",
        ScalarType::Bool => "bool",
        ScalarType::DateTime => "String",
        ScalarType::Bytes => "String",
        ScalarType::Json => "serde_json::Value",
    }
}

/// A valid Rust field identifier for a schema field name. SDL field names are
/// `[A-Za-z_][A-Za-z0-9_]*`, so the only adjustment needed is escaping Rust
/// keywords as raw identifiers (`type` -> `r#type`).
fn ident_for(name: &str) -> String {
    if is_raw_safe_keyword(name) {
        format!("r#{name}")
    } else if is_bare_keyword(name) {
        // Keywords that cannot be raw identifiers (`self`, `crate`, ...) — suffix.
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Keywords that are legal as raw identifiers (`r#name`).
fn is_raw_safe_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "break" | "const" | "continue" | "else" | "enum" | "false" | "fn" | "for" | "if"
            | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move" | "mut" | "pub" | "ref"
            | "return" | "static" | "struct" | "trait" | "true" | "type" | "unsafe" | "use"
            | "where" | "while" | "async" | "await" | "dyn" | "abstract" | "become" | "box"
            | "do" | "final" | "macro" | "override" | "priv" | "typeof" | "unsized" | "virtual"
            | "yield" | "try"
    )
}

/// The handful of keywords that are NOT valid as raw identifiers.
fn is_bare_keyword(name: &str) -> bool {
    matches!(name, "crate" | "self" | "super" | "Self")
}

#[cfg(test)]
mod tests {
    use super::*;
    use rhypedb_schema::parser::parse_schema;

    fn gen_rs(sdl: &str) -> String {
        generate_rust(&parse_schema(sdl).unwrap())
    }

    #[test]
    fn emits_typed_scalar_struct_with_constants() {
        let code = gen_rs(r#"type User { name: String @unique  age: i64 @indexed  active: Bool }"#);
        assert!(code.contains("pub struct User {"));
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains("pub age: Option<i64>,"));
        assert!(code.contains("pub active: Option<bool>,"));
        assert!(code.contains("pub const TYPE_NAME: &'static str = \"User\";"));
        assert!(code.contains(r#"pub const FIELDS: &'static [&'static str] = &["name", "age", "active"];"#));
    }

    #[test]
    fn maps_every_scalar_kind() {
        let code = gen_rs(
            r#"type T {
                s: String  a: u32  b: u64  c: i32  d: i64  e: f32  f: f64
                g: Bool  h: DateTime  i: Bytes  j: Json
            }"#,
        );
        for needle in [
            "pub s: Option<String>,",
            "pub a: Option<u32>,",
            "pub b: Option<u64>,",
            "pub c: Option<i32>,",
            "pub d: Option<i64>,",
            "pub e: Option<f32>,",
            "pub f: Option<f64>,",
            "pub g: Option<bool>,",
            "pub h: Option<String>,",  // DateTime -> String
            "pub i: Option<String>,",  // Bytes -> String
            "pub j: Option<serde_json::Value>,",
        ] {
            assert!(code.contains(needle), "missing `{needle}` in:\n{code}");
        }
    }

    #[test]
    fn relations_and_vectors_are_doc_comments_not_fields() {
        let code = gen_rs(
            r#"
            type Author {
                name: String
                books: [Book] @inverse(Book.author)
                bio_vec: Vector<384>
            }
            type Book { title: String  author: Author }
            "#,
        );
        // Relation + vector documented, not emitted as struct fields.
        assert!(code.contains("/// - relation `books` -> `Book` (many)"));
        assert!(code.contains("/// - vector `bio_vec` (dim 384)"));
        assert!(!code.contains("pub books:"));
        assert!(!code.contains("pub bio_vec:"));
        // Only the scalar `name` is a field; FIELDS reflects that.
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains(r#"pub const FIELDS: &'static [&'static str] = &["name"];"#));
    }

    #[test]
    fn keyword_field_becomes_raw_ident_with_serde_rename() {
        let code = gen_rs(r#"type Event { type: String  match: i64 }"#);
        assert!(code.contains("#[serde(default, rename = \"type\")]"));
        assert!(code.contains("pub r#type: Option<String>,"));
        assert!(code.contains("pub r#match: Option<i64>,"));
    }

    #[test]
    fn types_are_sorted_for_determinism() {
        let code = gen_rs(r#"type Zebra { a: i32 }  type Apple { b: i32 }  type Mango { c: i32 }"#);
        let apple = code.find("struct Apple").unwrap();
        let mango = code.find("struct Mango").unwrap();
        let zebra = code.find("struct Zebra").unwrap();
        assert!(apple < mango && mango < zebra, "types must be name-sorted");
    }

    #[test]
    fn emits_query_runtime_and_typed_constructors() {
        let code = gen_rs(r#"type User { name: String  age: i64 }"#);
        // Generic runtime types emitted once.
        assert!(code.contains("pub struct Query<T>"));
        assert!(code.contains("pub struct Row<T>"));
        assert!(code.contains("pub fn from_response(resp: &serde_json::Value)"));
        assert!(code.contains("pub fn filter(mut self, predicate: &str) -> Self"));
        assert!(code.contains("pub fn limit(mut self, n: u64) -> Self"));
        // Per-type typed constructors.
        assert!(code.contains("pub fn all() -> Query<User> { Query::raw(String::from(\"User\")) }"));
        assert!(code.contains("pub fn get(id: u64) -> Query<User> { Query::raw(format!(\"User.get({id})\")) }"));
        assert!(code.contains("pub fn filter(predicate: &str) -> Query<User> { Query::raw(format!(\"User.filter({predicate})\")) }"));
    }

    #[test]
    fn output_is_syntactically_valid_rust() {
        let code = gen_rs(
            r#"
            type User {
                name: String @unique
                age: i64 @indexed
                type: Bool
                posts: [Post] @inverse(Post.author) @on_delete(cascade)
                embedding: Vector<384> @vectorize(source: "name", model: "m") @index(hnsw, metric: cosine)
                meta: Json
                created: DateTime
                blob: Bytes
            }
            type Post { title: String  author: User }
            type Empty { only_a_relation: User }
            "#,
        );
        syn::parse_file(&code)
            .unwrap_or_else(|e| panic!("generated code is not valid Rust: {e}\n---\n{code}"));
    }
}
