// Code generated by rhypedb-codegen — DO NOT EDIT.
//
// Typed row structs + query seeds for a rhypedb schema, targeting the official
// `rhypedb-client`. Each struct mirrors an object type's scalar fields; the seed
// constructors (`User::all()`, `User::get(id)`, `User::filter(..)`,
// `User::create(&row)`) return a `rhypedb_client::Query<Self>` you hand to a
// `rhypedb_client::Client` (`client.fetch` / `fetch_one` / `create` / `execute`).
// Results come back as `rhypedb_client::Row<T>` (re-exported below as `Row`).
//
// Fields are `Option<T>` so a column-projected/partial response still
// deserializes. Relations and vector fields are documented per struct but are not
// scalar columns. `DateTime` reads/writes as an RFC 3339 `String`, `Bytes` as a
// base64 `String`, and `Json` as a `serde_json::Value`.
//
// Use as a module, e.g. `mod client;`. Requires the `rhypedb-client`, `serde`
// (with `derive`), and `serde_json` crates.

#![allow(dead_code, unused_imports)]

pub use rhypedb_client::{Query, Row};
use serde::{Deserialize, Serialize};

/// Quote + escape a string as a rhypedb query string literal.
fn rhypedb_str_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Format a numeric/bool value as a query literal. `Debug` keeps floats
/// float-shaped (`1.0`, `1.5`, `1e20`) and ints int-shaped (`30`); both coerce to
/// the field's declared scalar type on the server.
fn rhypedb_lit<T: std::fmt::Debug>(v: &T) -> String {
    format!("{v:?}")
}

/// Format a JSON value as a raw rhypedb JSON literal — the query parser accepts a
/// JSON object/array in value position; scalar JSON values round-trip too.
fn rhypedb_json_lit(v: &serde_json::Value) -> String {
    v.to_string()
}

/// Scalar fields of `type Doc`.
/// - vector `embedding` (dim 4)
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Doc {
    #[serde(default)]
    pub label: Option<String>,
}

impl Doc {
    pub const TYPE_NAME: &'static str = "Doc";
    pub const FIELDS: &'static [&'static str] = &["label"];

    /// `Doc` — all objects of this type.
    pub fn all() -> Query<Doc> { Query::all("Doc") }
    /// `Doc.get(id)` — one object by id.
    pub fn get(id: u64) -> Query<Doc> { Query::get("Doc", id) }
    /// `Doc.filter(predicate)` — e.g. `Doc::filter(".age > 18")`.
    pub fn filter(predicate: &str) -> Query<Doc> { Query::filter_on("Doc", predicate) }

    /// `Doc.create({ .. })` from this row's set (`Some`) fields.
    pub fn create(row: &Doc) -> Query<Doc> {
        let mut parts: Vec<String> = Vec::new();
        if let Some(v) = &row.label { parts.push(format!("label: {}", rhypedb_str_lit(v))); }
        Query::raw(format!("Doc.create({{ {} }})", parts.join(", ")))
    }
}

/// Scalar fields of `type Post`.
/// - relation `author` -> `User`
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Post {
    #[serde(default)]
    pub title: Option<String>,
}

impl Post {
    pub const TYPE_NAME: &'static str = "Post";
    pub const FIELDS: &'static [&'static str] = &["title"];

    /// `Post` — all objects of this type.
    pub fn all() -> Query<Post> { Query::all("Post") }
    /// `Post.get(id)` — one object by id.
    pub fn get(id: u64) -> Query<Post> { Query::get("Post", id) }
    /// `Post.filter(predicate)` — e.g. `Post::filter(".age > 18")`.
    pub fn filter(predicate: &str) -> Query<Post> { Query::filter_on("Post", predicate) }

    /// `Post.create({ .. })` from this row's set (`Some`) fields.
    pub fn create(row: &Post) -> Query<Post> {
        let mut parts: Vec<String> = Vec::new();
        if let Some(v) = &row.title { parts.push(format!("title: {}", rhypedb_str_lit(v))); }
        Query::raw(format!("Post.create({{ {} }})", parts.join(", ")))
    }
}

/// Scalar fields of `type User`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct User {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub age: Option<u32>,
    #[serde(default)]
    pub active: Option<bool>,
}

impl User {
    pub const TYPE_NAME: &'static str = "User";
    pub const FIELDS: &'static [&'static str] = &["name", "age", "active"];

    /// `User` — all objects of this type.
    pub fn all() -> Query<User> { Query::all("User") }
    /// `User.get(id)` — one object by id.
    pub fn get(id: u64) -> Query<User> { Query::get("User", id) }
    /// `User.filter(predicate)` — e.g. `User::filter(".age > 18")`.
    pub fn filter(predicate: &str) -> Query<User> { Query::filter_on("User", predicate) }

    /// `User.create({ .. })` from this row's set (`Some`) fields.
    pub fn create(row: &User) -> Query<User> {
        let mut parts: Vec<String> = Vec::new();
        if let Some(v) = &row.name { parts.push(format!("name: {}", rhypedb_str_lit(v))); }
        if let Some(v) = &row.age { parts.push(format!("age: {}", rhypedb_lit(v))); }
        if let Some(v) = &row.active { parts.push(format!("active: {}", rhypedb_lit(v))); }
        Query::raw(format!("User.create({{ {} }})", parts.join(", ")))
    }
}
