[package]
name = "rhypedb-engine"
version.workspace = true
edition.workspace = true

[dependencies]
rhypedb-storage = { workspace = true }
rhypedb-schema = { workspace = true }
rhypedb-vector = { workspace = true }
rhypedb-embed = { workspace = true }
rhypedb-subscribe = { workspace = true }
bytes = { workspace = true }
serde_json = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
